---
release: ocata

tag: 'sept-2016-elections'

timeframe:
  name: 'Mitaka-Newton'
  start: '2015-09-05T00:00'
  end: '2016-09-04T23:59'
  email_deadline: '2016-09-18T23:59'

tc_seats: 6

timeline:
  - name: 'PTL nomination'
    start: '2016-09-12T00:00'
    end: '2016-09-18T23:45'
  - name: 'PTL elections'
    start: '2016-09-19T00:00'
    end: '2016-09-25T23:45'
  - name: 'TC nomination'
    start: '2016-09-26T00:00'
    end: '2016-10-01T23:45'
  - name: 'TC elections'
    start: '2016-10-03T00:00'
    end: '2016-10-09T23:45'

past_elections:
  - ocata
