---
release: stein
election_type: tc

tag: 'sept-2018-elections'

timeframe:
  name: 'Queens-Rocky'
  # Beginning of the pike RC1/branch point for queens
  start: '2017-08-11T00:00'
  end: '2018-08-30T00:00'
  # Email deadline, to give officials the campaign/ptg week to
  # generate and verify rolls
  email_deadline: '2018-09-09T00:00'

tc_seats: 6

timeline:
  - name:  'TC Nominations'
    start: '2018-08-30T23:45'
    end:   '2018-09-06T23:45'
  - name:  'TC Campaigning'
    start: '2018-09-06T23:45'
    end:   '2018-09-18T23:45'
  - name:  'TC Elections'
    start: '2018-09-18T23:45'
    end:   '2018-09-27T23:45'
