---
release: queens

tag: 'aug-2017-elections'

timeframe:
  name: 'Ocata-Pike'
  start: '2016-09-16T23:59'
  end: '2017-08-03T23:59'
  email_deadline: '2017-08-05T23:59'

tc_seats: 7

timeline:
  - name: 'PTL nomination'
    start: '2017-07-31T23:59'
    end:   '2017-08-09T23:45'
  - name: 'PTL elections'
    start: '2017-08-09T23:59'
    end:   '2017-08-16T23:45'
