---
release: train
election_type: tc
tag: feb-2019-elections
tc_seats: 7
timeframe:
  name: Rocky-Stein
  start: 2018-02-09T00:00
  end: 2019-02-19T00:00
  email_deadline: 2019-02-19T00:00
timeline:
  - name:  'TC Nominations'
    start: '2019-02-12T23:45'
    end:   '2019-02-19T23:45'
  - name:  'TC Campaigning'
    start: '2019-02-19T23:45'
    end:   '2019-02-26T23:45'
  - name:  'TC Elections'
    start: '2019-02-26T23:45'
    end:   '2019-03-05T23:45'
