---
release: rocky

tag: 'feb-2018-elections'

timeframe:
  name: 'Pike-Queens'
  start: '2017-08-30T23:59'
  end: '2018-01-29T23:59'
  email_deadline: '2018-02-01T00:00'

tc_seats: 6

timeline:
  - name: 'PTL Nomination'
    start: '2018-01-29T23:59'
    end:   '2018-02-7T23:45'
  - name: 'PTL Election'
    start: '2018-02-07T23:59'
    end:   '2018-02-14T23:45'
