---
release: pike

tag: 'jan-2017-elections'

timeframe:
  name: 'Newton-Ocata'
  start: '2016-04-11T00:00'
  end: '2017-01-23T23:59'
  email_deadline: '2017-01-25T23:59'

tc_seats: 7

timeline:
  - name: 'PTL nomination'
    start: '2017-01-18T23:59'
    end:   '2017-01-29T23:45'
  - name: 'PTL elections'
    start: '2017-02-01T23:59'
    end:   '2017-02-07T23:45'

past_elections:
  - ocata
