---
release: train
election_type: ptl
tag: feb-2019-elections
tc_seats: 7
timeframe:
  name: Rocky-Stein
  start: 2018-02-09T00:00
  end: 2019-02-19T00:00
  email_deadline: 2019-02-22T00:00
timeline:
  - name: PTL Nominations
    start: 2019-03-05T23:45
    end: 2019-03-12T23:45
  - name: PTL Election
    start: 2019-03-12T23:45
    end: 2019-03-19T23:45
