- project:
    templates:
      - build-openstack-sphinx-docs
      - openstack-python35-jobs
    check:
      jobs:
        - openstack-tox-py27
        - openstack-tox-linters
        - election-tox-ci-checks:
            voting: false
    gate:
      jobs:
        - openstack-tox-py27
        - openstack-tox-linters
    post:
      jobs:
        - publish-static
